### ISSUE TITLE
刷视频的时候不滑动屏幕，只能刷同一个视频

### ISSUE THREAD

**Issue by Peachliu** [readmagic/loveStudy#3]
文件名、目录名或卷标语法不正确。
正在观看视频... 成达万高铁重庆段全面开工建设
正在观看视频... 江苏连云港：中国鲜切花第一镇，幸福生活像花儿一样
文件名、目录名或卷标语法不正确。
正在观看视频... 成达万高铁重庆段全面开工建设
文件名、目录名或卷标语法不正确。
正在观看视频... 拾荒助学的浙大退休教师：生命不息，爱心事业不止！
文件名、目录名或卷标语法不正确。
正在观看视频... 拾荒助学的浙大退休教师：生命不息，爱心事业不止！
文件名、目录名或卷标语法不正确。
正在观看视频... 拾荒助学的浙大退休教师：生命不息，爱心事业不止！

**Comment by Peachliu** [comment]
看文章也是，不会上下滑动屏幕，导致如果锁屏时间短会自动锁屏，然后就出错了

**Comment by Peachliu** [comment]
另外就是看本地频道的时候，因为是设定了 上海，导致定位如果不是上海的就会出错

**Comment by Peachliu** [comment]
感谢回复，本地频道的我直接修改了，滑动屏幕这个我再研究一下，请问你说的adb滑动屏幕是指令没找到，这个不太明白，还请赐教
另外，再次感谢你的这个程序，看到另外一种可能，谢谢

**Comment by Peachliu** [comment]
谢谢回复，之前那个地方我改了，因为我用的win，所以直接修改成了D:\tool\adb，也就是adb在系统path里面的路径，刚才去直接修改成了"adb"，似乎可以滑动了，没报之前的“文件名、目录名……”这样的错误，不过可能滑动屏幕的力度还需要调试，没办法准确的进入需要完成的项目，看了一下swipe_down这个方法，没太明白，不知道能不能说说怎么调整呢？我的手机是oppo find x3

**Comment by Peachliu** [comment]
刚才换了台小米设备 max3 试了一下，出现了这个错误
`已登录
每日答题开始.
Traceback (most recent call last):
  File "D:\loveStudy\Main.py", line 72, in one_account
    task(mobile, password)
  File "D:\loveStudy\Main.py", line 53, in task
    AnswerTask.answer(mobile)
  File "D:\loveStudy\AnswerTask.py", line 18, in answer
    if __daily_question__():
  File "D:\loveStudy\AnswerTask.py", line 129, in __daily_question__
    Config.DRIVER.click(x1, y1)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 1038, in click
    x, y = self.pos_rel2abs(x, y)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 970, in _convert
    assert x >= 0
AssertionError`
